CREATE TABLE pedidos (
  id int4 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
  data_hora date NOT NULL,
  status varchar(255) NOT NULL,
  PRIMARY KEY (id)
)



